# Generated by Django 5.1.6 on 2025-02-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='us_id', db_index=True, primary_key=True, serialize=False)),
                ('name1', models.CharField(db_collation='utf8mb3_general_ci', db_column='us_name1', max_length=150)),
                ('name2', models.CharField(db_collation='utf8mb3_general_ci', db_column='us_name2', max_length=150)),
                ('name3', models.CharField(db_collation='utf8mb3_general_ci', db_column='us_name3', max_length=150)),
                ('date_of_birth', models.DateField(db_column='us_date_of_birth')),
                ('sex', models.CharField(db_collation='utf8mb3_general_ci', db_column='us_sex', default='M', max_length=1)),
                ('adress', models.CharField(db_collation='utf8mb3_general_ci', db_column='us_adress', max_length=150)),
                ('phone', models.CharField(db_collation='utf8mb3_general_ci', db_column='us_phone', max_length=150)),
                ('e_mail', models.CharField(db_collation='utf8mb3_general_ci', db_column='us_e_mail', max_length=150)),
                ('password', models.CharField(db_collation='utf8mb3_general_ci', db_column='us_password', max_length=32)),
                ('description', models.CharField(db_collation='utf8mb3_general_ci', db_column='us_description', max_length=300)),
                ('hash', models.CharField(db_collation='utf8mb3_general_ci', db_column='us_hash', max_length=32)),
                ('reward', models.FloatField(blank=True, db_column='us_reward', default=0, null=True)),
                ('autor0', models.IntegerField(db_column='us_autor0')),
                ('date0', models.DateTimeField(db_column='us_date0')),
                ('autor1', models.IntegerField(db_column='us_autor1')),
                ('date1', models.DateTimeField(db_column='us_date1')),
                ('deleted_mark', models.IntegerField(db_column='us_deleted_mark', default=0)),
                ('deleted', models.IntegerField(db_column='us_deleted', default=0)),
                ('login', models.CharField(db_collation='utf8mb3_general_ci', db_column='us_login', max_length=30)),
                ('allowed_objects', models.CharField(db_collation='utf8mb3_general_ci', db_column='us_allowed_objects', default='0', max_length=2048)),
                ('personal_desktop', models.IntegerField(db_column='us_personal_desktop', default=0)),
                ('max_discount', models.IntegerField(blank=True, db_column='max_discount', null=True)),
                ('allowed_debt', models.IntegerField(blank=True, db_column='allowed_debt', null=True)),
                ('allow_clear_receipt', models.IntegerField(blank=True, db_column='allow_clear_receipt', null=True)),
                ('allow_shift', models.IntegerField(blank=True, db_column='allow_shift', null=True)),
                ('passw', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='us_pass', max_length=255, null=True)),
            ],
            options={
                'db_table': 'dir_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.AutoField(db_column='usgrp_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb3_general_ci', db_column='usgrp_name', default='-', max_length=150)),
                ('deleted', models.IntegerField(db_column='usgrp_deleted', default=0)),
            ],
            options={
                'db_table': 'dir_users_groups',
                'managed': False,
            },
        ),
    ]
